### ISSUE TITLE
Adjust the "Your rating" text after rating set

### ISSUE THREAD

**Issue by magnusarinell** [magnusarinell/istoriez.com#11]
At the end of each story a user has the possibility to rate the story by setting stars. The title for the unset stars says "Your rating", and the title after a rating has been set also says "Your rating". Showing another text after a rating has been set would provide a better cue to the user that the rating has been received by iStoriez.

**Comment by dvdksn** [comment]
I'd like to give this a shot

**Comment by magnusarinell** [comment]
Great! 🙂
